//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36392
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.BookServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SQLError", Namespace="http://schemas.datacontract.org/2004/07/BookMgr.Common")]
    [System.SerializableAttribute()]
    public partial class SQLError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationField, value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookServiceRef.IBookService")]
    public interface IBookService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Add", ReplyAction="http://tempuri.org/IBookService/AddResponse")]
        string Add(string mbook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Add", ReplyAction="http://tempuri.org/IBookService/AddResponse")]
        System.Threading.Tasks.Task<string> AddAsync(string mbook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Edit", ReplyAction="http://tempuri.org/IBookService/EditResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.BookServiceRef.SQLError), Action="http://tempuri.org/IBookService/EditSQLErrorFault", Name="SQLError", Namespace="http://schemas.datacontract.org/2004/07/BookMgr.Common")]
        string Edit(string mbook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Edit", ReplyAction="http://tempuri.org/IBookService/EditResponse")]
        System.Threading.Tasks.Task<string> EditAsync(string mbook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Get", ReplyAction="http://tempuri.org/IBookService/GetResponse")]
        string Get(string bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Get", ReplyAction="http://tempuri.org/IBookService/GetResponse")]
        System.Threading.Tasks.Task<string> GetAsync(string bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Delete", ReplyAction="http://tempuri.org/IBookService/DeleteResponse")]
        string Delete(string bookInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Delete", ReplyAction="http://tempuri.org/IBookService/DeleteResponse")]
        System.Threading.Tasks.Task<string> DeleteAsync(string bookInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookServiceChannel : ConsoleApplication1.BookServiceRef.IBookService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookServiceClient : System.ServiceModel.ClientBase<ConsoleApplication1.BookServiceRef.IBookService>, ConsoleApplication1.BookServiceRef.IBookService {
        
        public BookServiceClient() {
        }
        
        public BookServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Add(string mbook) {
            return base.Channel.Add(mbook);
        }
        
        public System.Threading.Tasks.Task<string> AddAsync(string mbook) {
            return base.Channel.AddAsync(mbook);
        }
        
        public string Edit(string mbook) {
            return base.Channel.Edit(mbook);
        }
        
        public System.Threading.Tasks.Task<string> EditAsync(string mbook) {
            return base.Channel.EditAsync(mbook);
        }
        
        public string Get(string bookId) {
            return base.Channel.Get(bookId);
        }
        
        public System.Threading.Tasks.Task<string> GetAsync(string bookId) {
            return base.Channel.GetAsync(bookId);
        }
        
        public string Delete(string bookInfo) {
            return base.Channel.Delete(bookInfo);
        }
        
        public System.Threading.Tasks.Task<string> DeleteAsync(string bookInfo) {
            return base.Channel.DeleteAsync(bookInfo);
        }
    }
}
